
name: 'Project_DBT_intermediate'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:        
  - "target"
  - "dbt_packages"


# Esto también se puede editar dentro del notebook mediante {{ config(materialized='table') }} o {{ config(materialized='view') }}
models:
  Project_DBT_intermediate:
    
    #1. Capa de Staging: Por defecto todo como tabla
    staging:x
      +materialized: table
      tpch:
        stg_tpch_orders:
          +materialized: incremental # Solo esta será incremental

    #2. Capa de Transformation: Vistas
    transformation:
      +materialized: view

    #3. Capa Business: Tablas
    business:
      +materialized: table
      +schema: business