version: 2

models:
  - name: fct_sales
    description: "Tabla de hechos principal que contiene todas las transacciones de venta."
    columns:
      - name: lineitem_key
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments: # Los argumentos SIEMPRE bajo 'arguments'
                to: ref('dim_customers')
                field: customer_id
              config:
                severity: error

      - name: net_sales_amount
        description: "Monto neto de la venta tras descuentos."
        tests:
          - is_positive:
              config:
                severity: error

  - name: dim_customers
    description: "Dimensión que contiene la información maestra de los clientes."
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

      - name: customer_name
        tests:
          - is_not_empty:
              config:
                severity: warn

      - name: country
        tests:
          - accepted_values:
              arguments: # Corregimos la deprecación dbt102
                values: ['ALGERIA', 'ARGENTINA', 'BRAZIL', 'CANADA', 'EGYPT', 'ETHIOPIA', 'FRANCE', 'GERMANY', 'INDIA', 'INDONESIA', 'IRAN', 'IRAQ', 'JAPAN', 'JORDAN', 'KENYA', 'MOROCCO', 'MOZAMBIQUE', 'PERU', 'CHINA', 'ROMANIA', 'SAUDI ARABIA', 'VIETNAM', 'RUSSIA', 'UNITED KINGDOM', 'UNITED STATES']
              config:
                severity: warn

  - name: dim_parts_suppliers
    description: "Dimensión que consolida la información de productos y sus proveedores."
    columns:
      - name: partsupp_key
        tests:
          - unique
          - not_null